version: '3.7'

services:
  canbot:
    container_name: canbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./bot.db:/usr/src/app/bot.db
      - ./conf.json:/usr/src/app/conf.json
      - ./var:/usr/src/app/var
      - ./sessions:/usr/src/app/sessions
    ports:
      - "8068:8068"
    restart: unless-stopped
